CREATE TABLE IF NOT EXISTS post_like(
post_id INT NOT NULL,
user_id VARCHAR(20) NOT NULL,
PRIMARY KEY(post_id, user_id),
FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(post_id) REFERENCES post(post_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;