CREATE TABLE IF NOT EXISTS vote_user_answer(
answer_id INT NOT NULL AUTO_INCREMENT,
vote_id INT NOT NULL,
que_id INT NOT NULL,
select_id INT NULL,
user_id VARCHAR(20) NULL,
answer VARCHAR(500) NULL DEFAULT NULL,
PRIMARY KEY(answer_id),
FOREIGN KEY(vote_id) REFERENCES vote(vote_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(que_id) REFERENCES vote_que(que_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(select_id) REFERENCES vote_select(select_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE SET NULL ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;