CREATE TABLE IF NOT EXISTS post_attach(
post_id INT NOT NULL,
file_path VARCHAR(500) NOT NULL,
PRIMARY KEY(post_id, file_path),
FOREIGN KEY(post_id) REFERENCES post(post_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;