CREATE TABLE IF NOT EXISTS vote_que(
que_id INT NOT NULL AUTO_INCREMENT,
vote_id INT NOT NULL,
que VARCHAR(100) NOT NULL,
que_type TINYINT NOT NULL,
PRIMARY KEY(que_id),
FOREIGN KEY(vote_id) REFERENCES vote(vote_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;