CREATE TABLE IF NOT EXISTS post_comment(
comment_id INT NOT NULL AUTO_INCREMENT,
post_id INT NOT NULL,
user_id VARCHAR(20) NULL,
comment VARCHAR(500) NOT NULL,
comment_anony TINYINT NOT NULL DEFAULT 0,
comment_date DATETIME NOT NULL DEFAULT NOW(),
comment_parent INT NULL DEFAULT NULL,
PRIMARY KEY(comment_id),
FOREIGN KEY(post_id) REFERENCES post(post_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE SET NULL ON UPDATE CASCADE,
FOREIGN KEY(comment_parent) REFERENCES post_comment(comment_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;