CREATE TABLE IF NOT EXISTS vote_select(
select_id INT NOT NULL AUTO_INCREMENT,
que_id INT NOT NULL,
select_content VARCHAR(100) NOT NULL,
PRIMARY KEY(select_id),
FOREIGN KEY(que_id) REFERENCES vote_que(que_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;