CREATE TABLE IF NOT EXISTS user_tag(
user_id VARCHAR(20) NOT NULL,
tag_id VARCHAR(20) NOT NULL,
PRIMARY KEY(user_id, tag_id),
FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(tag_id) REFERENCES tag(tag_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;