CREATE TABLE IF NOT EXISTS log(
log_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
user_id VARCHAR(20) NULL,
log_url VARCHAR(100) NOT NULL,
log_time DATETIME NOT NULL DEFAULT NOW(),
PRIMARY KEY(log_id),
FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE SET NULL ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;